#!/bin/bash -e

echo "build on progress"

docker build -q -t wa-api .

if [ $? -eq 0 ]; then
   echo OK, build success
   echo "Running project..."
   docker rm wa-api
   docker run -it -p 5100:5100 -v ${pwd}:/src --cap-add=SYS_ADMIN --env-file ./env.list --name wa-api wa-api
   if [ $? -eq 0 ]; then
      echo "Running Project Fail"
   fi
else
   echo FAIL, image not created
   exit 1
fi

